import React, { useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import { apiFetchAuth, getApiStatus } from "./lib/api";
import { logout, signInWithApple, signInWithEmail, signInWithGoogle, signUpWithEmail, subscribeToAuth, syncCurrentUser } from "./lib/auth";
import type { User } from "firebase/auth";
import "./styles.css";

type Page = "dashboard"|"orders"|"customers"|"products"|"inventory"|"purchases"|"payments"|"delivery"|"reports"|"analytics"|"routes"|"visits"|"promotions"|"tasks"|"team"|"branches"|"integrations"|"settings";
type Row = Record<string, any>;
type ApiState = {status:"loading"}|{status:"online";version:string}|{status:"offline";message:string};

const navGroups:any[]=[
 {label:"Overview",items:[["dashboard","Dashboard","⌂"],["analytics","Analytics & BI","◒"]]},
 {label:"Sales",items:[["orders","Orders","↗"],["customers","Customers","◎"],["routes","Routes","⌁"],["visits","Visits","✓"],["promotions","Promotions","%"]]},
 {label:"Catalog & stock",items:[["products","Products","▦"],["inventory","Inventory","▤"],["purchases","Purchases","↓"],["delivery","Delivery","⇢"]]},
 {label:"Finance",items:[["payments","Payments & debts","₮"],["reports","Reports","▥"]]},
 {label:"Management",items:[["tasks","Tasks","☑"],["team","Team","♙"],["branches","Branches","⌂"],["integrations","Integrations","↔"]]},
 {label:"System",items:[["settings","Settings","⚙"]]},
];

const cfg:any={
 customers:{title:"Customers",sub:"Accounts, contacts, credit limits and customer history.",endpoint:"customers",action:"Add customer",fields:[["name","Name"],["phone","Phone"],["address","Address"],["creditLimit","Credit limit"]],cols:["name","code","phone","creditLimit","isActive"]},
 products:{title:"Products",sub:"Master catalog, SKU, barcode, cost and selling prices.",endpoint:"products",action:"Add product",fields:[["name","Name"],["sku","SKU"],["unit","Unit"],["barcode","Barcode"],["costPrice","Cost price"],["salePrice","Sale price"]],cols:["name","sku","unit","costPrice","salePrice","isActive"]},
 orders:{title:"Orders",sub:"Order lifecycle from draft through confirmation and completion.",endpoint:"orders",action:"New order",fields:[["customerId","Customer ID"],["notes","Notes"]],cols:["orderNumber","customer","status","total","createdAt"]},
 inventory:{title:"Inventory",sub:"Live stock by warehouse and SKU.",endpoint:"inventory",action:"Stock transfer",fields:[],cols:["warehouse","product","sku","quantity"]},
 purchases:{title:"Purchases",sub:"Supplier purchasing and inbound stock workflow.",endpoint:"purchases",action:"New purchase",fields:[["name","Supplier name"],["phone","Phone"]],cols:["name","code","phone"]},
 payments:{title:"Payments & debts",sub:"Collections, payment references and receivables control.",endpoint:"payments",action:"Record payment",fields:[["orderId","Order ID"],["customerId","Customer ID"],["amount","Amount"],["method","Method"],["reference","Reference"]],cols:["customerId","amount","method","status","reference","createdAt"]},
 delivery:{title:"Delivery",sub:"Prepare, dispatch, track and confirm delivery.",endpoint:"deliveries",action:"Create delivery",fields:[["orderId","Order ID"],["address","Address"],["plannedAt","Planned time"]],cols:["orderNumber","customer","status","address","plannedAt"]},
 routes:{title:"Routes",sub:"Plan field routes and assign owners to outlet visits.",endpoint:"routes",action:"Create route",fields:[["name","Route name"],["routeDate","Date"],["notes","Notes"]],cols:["name","routeDate","status","notes"]},
 visits:{title:"Visits",sub:"Digital outlet visits, outcomes, notes and execution history.",endpoint:"visits",action:"Start visit",fields:[["customerId","Customer ID"],["routeId","Route ID"],["notes","Notes"]],cols:["customer","status","outcome","notes","createdAt"]},
 promotions:{title:"Promotions",sub:"Plan promotions, target customers and track execution.",endpoint:"promotions",action:"New promotion",fields:[["name","Name"],["discount","Discount"],["startDate","Start"],["endDate","End"],["notes","Notes"]],cols:["name","status","discount","startDate","endDate"]},
 tasks:{title:"Tasks",sub:"Operational signals become owned, deadline-driven actions.",endpoint:"tasks",action:"Create task",fields:[["title","Title"],["description","Description"],["priority","Priority"],["dueAt","Due date"]],cols:["title","status","priority","dueAt"]},
 team:{title:"Team",sub:"Users, responsibilities and access within the company.",endpoint:"team",action:"Invite member",fields:[],cols:["fullName","email","phone","status","createdAt"]},
 branches:{title:"Branches",sub:"Operating locations, warehouses and branch-level control.",endpoint:"branches",action:"Add branch",fields:[["name","Name"],["code","Code"],["address","Address"],["phone","Phone"]],cols:["name","code","address","phone","isActive"]},
 integrations:{title:"Integrations",sub:"ERP, payment, fiscal and external data connections.",endpoint:"integrations",action:"Add integration",fields:[["name","Name"],["provider","Provider"],["endpoint","Endpoint"]],cols:["name","provider","status","lastSyncAt"]},
 reports:{title:"Reports",sub:"Operational summaries based on real records in your workspace.",endpoint:"reports/summary",action:"Refresh",fields:[],cols:["metric","value"]},
};

function Badge({children}:{children:any}){const s=String(children??"").toLowerCase();const cls=s.includes("completed")||s.includes("paid")||s.includes("active")||s.includes("healthy")||s.includes("confirmed")||s.includes("delivered")?"good":s.includes("low")||s.includes("pending")||s.includes("processing")||s.includes("draft")||s.includes("planned")||s.includes("in_progress")?"warn":"bad";return <span className={"badge "+cls}>{children??"—"}</span>}
function money(v:any){const n=Number(v);return Number.isFinite(n)?new Intl.NumberFormat("en-US").format(n)+" UZS":String(v??"—")}
function label(k:string){return ({creditLimit:"Credit limit",costPrice:"Cost",salePrice:"Price",isActive:"Status",orderNumber:"Order",createdAt:"Created",routeDate:"Date",dueAt:"Due",startDate:"Start",endDate:"End",lastSyncAt:"Last sync",customerId:"Customer",warehouse:"Warehouse",product:"Product",quantity:"Quantity"} as any)[k]||k.replace(/[A-Z]/g,m=>" "+m).replace(/^./,m=>m.toUpperCase())}

function App(){
 const [user,setUser]=useState<User|null>(null); const [page,setPage]=useState<Page>("dashboard"); const [sidebar,setSidebar]=useState(true);
 const [api,setApi]=useState<ApiState>({status:"loading"}); const [authOpen,setAuthOpen]=useState(false); const [authMode,setAuthMode]=useState<"signIn"|"signUp">("signIn");
 const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [authBusy,setAuthBusy]=useState(false);const [authError,setAuthError]=useState("");const [toast,setToast]=useState("");
 useEffect(()=>subscribeToAuth(setUser),[]);
 useEffect(()=>{getApiStatus().then(x=>setApi({status:"online",version:x.version})).catch(e=>setApi({status:"offline",message:String(e)}))},[]);
 useEffect(()=>{if(user)void syncCurrentUser().catch(console.error)},[user]);
 useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(""),2600);return()=>clearTimeout(t)}},[toast]);
 const runAuth=async(fn:()=>Promise<any>)=>{setAuthBusy(true);setAuthError("");try{await fn();await syncCurrentUser();setAuthOpen(false);setToast("Welcome to MyBusiness.");}catch(e){setAuthError(e instanceof Error?e.message:"Authentication failed")}finally{setAuthBusy(false)}};
 if(!user)return <Welcome api={api} open={()=>setAuthOpen(true)} authOpen={authOpen} mode={authMode} setMode={setAuthMode} email={email} setEmail={setEmail} password={password} setPassword={setPassword} busy={authBusy} error={authError} setError={setAuthError} runAuth={runAuth}/>;
 const title=page==="dashboard"?"Dashboard":page==="analytics"?"Analytics & BI":page==="settings"?"Settings":(cfg[page]?.title||"MyBusiness");
 return <div className="workspace"><aside className={"sidebar "+(sidebar?"":"collapsed")}><div className="side-brand"><span className="logo">M</span>{sidebar&&<><strong>MyBusiness</strong><span className="workspace-label">Workspace</span></>}</div><div className="company-switch">{sidebar?<><span className="company-dot">{(user.displayName||"M").charAt(0)}</span><span><b>{user.displayName||"My Company"}</b><small>Owner · UZS</small></span></>:<span className="company-dot">M</span>}</div><nav className="side-nav">{navGroups.map(g=><div className="nav-group" key={g.label}>{sidebar&&<div className="nav-label">{g.label}</div>}{g.items.map((i:any)=><button className={"nav-item "+(page===i[0]?"active":"")} key={i[0]} onClick={()=>setPage(i[0])}><span className="nav-icon">{i[2]}</span>{sidebar&&<span>{i[1]}</span>}</button>)}</div>)}</nav>{sidebar&&<div className="side-bottom"><div className="api-mini"><i></i><span><b>System {api.status==="online"?"online":"checking"}</b><small>{api.status==="online"?"Services operational":"API status"}</small></span></div><button className="profile-mini" onClick={()=>setPage("settings")}><span className="avatar">{(user.displayName||user.email||"U").charAt(0).toUpperCase()}</span><span><b>{user.displayName||"Account"}</b><small>{user.email||"Signed in"}</small></span></button></div>}</aside>
 <div className="main-area"><header className="appbar"><button className="icon-btn" onClick={()=>setSidebar(v=>!v)}>☰</button><div className="crumb"><span>MyBusiness</span><b>/</b><strong>{title}</strong></div><div className="appbar-actions"><button className="icon-btn" onClick={()=>setToast("Use the module search and filters to find records.")}>⌕</button><button className="icon-btn" onClick={()=>setToast("Notifications are available in the API.")}>◔</button><div className="user-menu"><span className="avatar">{(user.displayName||user.email||"U").charAt(0).toUpperCase()}</span><span className="user-name">{user.displayName||user.email}</span><button className="icon-btn" onClick={()=>logout()}>↪</button></div></div></header><main className="content"><PageView page={page} tokenUser={user} toast={setToast} go={setPage}/></main></div>{toast&&<div className="toast">✓ {toast}</div>}</div>
}

function Welcome(p:any){return <div className="landing"><header className="landing-nav"><div className="brand"><span className="logo">M</span><b>MyBusiness</b></div><div><button className="button ghost" onClick={p.open}>Sign in</button><button className="button dark" onClick={()=>{p.setMode("signUp");p.open()}}>Create account</button></div></header><section className="landing-hero"><div><span className="eyebrow">Distribution operating system</span><h1>Your business.<br/><em>One workspace.</em></h1><p>Orders, customers, products, inventory, finance, field execution and reporting in one connected system.</p><div className="hero-actions"><button className="button primary" onClick={()=>{p.setMode("signUp");p.open()}}>Create workspace →</button><button className="button ghost" onClick={p.open}>Sign in</button></div><div className="landing-proof"><span>● Live operations</span><span>● PostgreSQL</span><span>● Role-based access</span></div></div><div className="landing-screen"><div className="screen-top"><b>Business overview</b><Badge>Live</Badge></div><div className="screen-metrics"><div><small>Live records</small><b>Connected</b><span>PostgreSQL</span></div><div><small>Operations</small><b>18 modules</b><span>Ready</span></div><div><small>Security</small><b>Company scoped</b><span>Firebase auth</span></div><div><small>API</small><b>Healthy</b><span>Monitored</span></div></div><div className="fake-chart"><div className="chart-title"><b>Operational workspace</b><small>Live data</small></div><div className="bars">{[42,55,48,68,61,75,58,82,72,90,78,96].map((h,i)=><i style={{height:h+"%"}} key={i}></i>)}</div></div></div></section>{p.authOpen&&<AuthModal {...p}/>}</div>}
function AuthModal(p:any){return <div className="modal-backdrop" onClick={()=>!p.busy&&p.setAuthOpen(false)}><div className="auth-modal" onClick={(e:any)=>e.stopPropagation()}><button className="modal-close" onClick={()=>p.setAuthOpen(false)}>×</button><span className="eyebrow">{p.mode==="signIn"?"Welcome back":"Get started"}</span><h2>{p.mode==="signIn"?"Sign in to your workspace":"Create your workspace"}</h2><p>Secure access to your company workspace.</p><div className="social-auth"><button className="button outline" disabled={p.busy} onClick={()=>p.runAuth(signInWithGoogle)}>G <span>Continue with Google</span></button><button className="button outline" disabled={p.busy} onClick={()=>p.runAuth(signInWithApple)}> <span>Continue with Apple</span></button></div><div className="or"><span>or continue with email</span></div><form onSubmit={(e:any)=>{e.preventDefault();void p.runAuth(()=>p.mode==="signIn"?signInWithEmail(p.email,p.password):signUpWithEmail(p.email,p.password))}}><label>Email<input type="email" value={p.email} onChange={(e:any)=>p.setEmail(e.target.value)} required/></label><label>Password<input type="password" value={p.password} onChange={(e:any)=>p.setPassword(e.target.value)} minLength={6} required/></label>{p.error&&<div className="auth-error">{p.error}</div>}<button className="button primary full" disabled={p.busy}>{p.busy?"Please wait…":p.mode==="signIn"?"Sign in":"Create account"}</button></form><button className="switch-auth" onClick={()=>{p.setMode(p.mode==="signIn"?"signUp":"signIn");p.setError("")}}>{p.mode==="signIn"?"Create a new account":"I already have an account"}</button></div></div>}

function PageView({page,tokenUser,toast,go}:{page:Page;tokenUser:User;toast:(s:string)=>void;go:(p:Page)=>void}){
 if(page==="dashboard")return <Dashboard user={tokenUser} go={go}/>;
 if(page==="analytics")return <Analytics user={tokenUser}/>;
 if(page==="settings")return <Settings toast={toast}/>;
 return <LiveModule page={page} user={tokenUser} toast={toast}/>;
}

function useApiData(endpoint:string,user:User){const [rows,setRows]=useState<Row[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const load=async()=>{setLoading(true);setError("");try{const t=await user.getIdToken();const d=await apiFetchAuth<any>("/api/v1/data/"+endpoint,t);if(Array.isArray(d))setRows(d);else if(d&&endpoint==="reports/summary")setRows(Object.entries(d).map(([metric,value])=>({metric,value})));else setRows([])}catch(e){setError(e instanceof Error?e.message:"Request failed")}finally{setLoading(false)}};useEffect(()=>{void load()},[endpoint,user.uid]);return {rows,setRows,loading,error,reload:load}}

function LiveModule({page,user,toast}:any){const c=cfg[page];const {rows,setRows,loading,error,reload}=useApiData(c.endpoint,user);const [search,setSearch]=useState("");const [open,setOpen]=useState(false);const filtered=useMemo(()=>rows.filter(r=>JSON.stringify(r).toLowerCase().includes(search.toLowerCase())),[rows,search]);
 const create=async(data:any)=>{try{const t=await user.getIdToken();const endpoint=page==="purchases"?"suppliers":c.endpoint;const d=await apiFetchAuth<any>("/api/v1/data/"+endpoint,t,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});setRows(x=>[d,...x]);setOpen(false);toast(c.action+" saved.");}catch(e){toast(e instanceof Error?e.message:"Could not save.");}};
 const stat=page==="reports"?[]:[["Records",rows.length],["Active",rows.filter(r=>String(r.status||r.isActive).toLowerCase().includes("active")||r.isActive===true).length],["Attention",rows.filter(r=>["low","pending","overdue","failed"].includes(String(r.status).toLowerCase())).length],["Updated","Live"]];
 return <div><PageHeader title={c.title} subtitle={c.sub} actions={<button className="button primary" onClick={()=>page==="reports"?void reload():setOpen(true)}>+ {c.action}</button>}/>{stat.length>0&&<div className="module-stat-grid">{stat.map((x:any,i:number)=><div className="module-stat" key={x[0]}><span className="module-stat-icon">{["◒","✓","!","↗"][i]}</span><small>{x[0]}</small><b>{x[1]}</b><span className={i===2?"warn":"good"}>{i===3?"Live data":"Current"}</span></div>)}</div>}<div className="toolbar"><div className="searchbox">⌕<input value={search} onChange={e=>setSearch(e.target.value)} placeholder={"Search "+c.title.toLowerCase()+"..."}/></div><button className="filter-btn" onClick={()=>setSearch("")}>Clear</button><span className="toolbar-count">{filtered.length} records</span></div><section className="panel table-panel">{loading?<div className="empty-work"><h3>Loading live data…</h3></div>:error?<div className="empty-work"><h3>Could not load data</h3><p>{error}</p><button className="button outline" onClick={()=>void reload()}>Retry</button></div>:filtered.length===0?<div className="empty-work"><h3>No records yet</h3><p>Create the first record to start using this module.</p></div>:<Table rows={filtered} columns={c.cols}/>}</section>{open&&<CreateModal config={c} close={()=>setOpen(false)} save={create}/>}</div>}

function CreateModal({config,close,save}:{config:any;close:()=>void;save:(d:any)=>void}){const [data,setData]=useState<any>({});return <div className="modal-backdrop"><div className="quick-modal"><button className="modal-close" onClick={close}>×</button><span className="eyebrow">Create record</span><h2>{config.action}</h2>{config.fields.length===0?<p>This action needs a linked record or workflow. You can use the API-backed module directly.</p>:config.fields.map((f:any)=><label key={f[0]}>{f[1]}<input value={data[f[0]]??""} onChange={e=>setData({...data,[f[0]]:e.target.value})} placeholder={f[1]}/></label>)}<div className="modal-actions"><button className="button outline" onClick={close}>Cancel</button><button className="button primary" onClick={()=>save(data)}>Save</button></div></div></div>}
function Dashboard({user,go}:{user:User;go:(p:Page)=>void}){const {rows,loading}=useApiData("dashboard",user);const d=rows[0]||{};return <div><PageHeader title="Business dashboard" subtitle="Live operational view from your company data." actions={<><button className="button outline" onClick={()=>go("reports")}>Reports</button><button className="button primary" onClick={()=>go("orders")}>+ New order</button></>}/><div className="dashboard-grid">{[["Completed sales",money(d.sales||0),"Live"],["Orders",d.orders??0,"Live"],["Customers",d.customers??0,"Live"],["Status",loading?"Loading":"Operational",loading?"":"API"]].map(x=><div className="kpi" key={x[0]}><div><small>{x[0]}</small><b>{x[1]}</b><span className="good">{x[2]}</span></div><i>↗</i></div>)}</div><div className="dashboard-columns"><section className="panel"><PanelHead title="Recent orders" action="Open orders" onClick={()=>go("orders")}/><Table rows={d.recent||[]} columns={["orderNumber","customer","total","status","createdAt"]}/></section><section className="panel"><PanelHead title="Operational controls"/><div className="alert-list">{[["Routes","routes"],["Visits","visits"],["Tasks","tasks"],["Inventory","inventory"]].map(x=><div key={x[0]}><span className="stock-symbol warn">→</span><span><b>{x[0]}</b><small>Open module</small></span><button className="button ghost" onClick={()=>go(x[1] as Page)}>Open</button></div>)}</div></section></div></div>}
function Analytics({user}:{user:User}){const f=useApiData("finance/summary",user);const r=useApiData("reports/summary",user);return <div><PageHeader title="Analytics & BI" subtitle="Decision metrics calculated from live sales, finance, inventory, tasks and visits." actions={<button className="button outline" onClick={()=>{void f.reload();void r.reload()}}>Refresh</button>}/><div className="analytics-grid">{[["Sales",f.rows[0]?.sales],["Collected",f.rows[0]?.collected],["Credit limits",f.rows[0]?.creditLimit],["Open tasks",r.rows.find(x=>x.metric==="openTasks")?.value]].map(x=><div className="kpi" key={x[0]}><div><small>{x[0]}</small><b>{typeof x[1]==="number"?money(x[1]):x[1]??"—"}</b><span className="good">Live</span></div><i>↗</i></div>)}</div><section className="panel report-builder"><PanelHead title="Operational summary"/><Table rows={r.rows} columns={["metric","value"]}/></section></div>}
function Settings({toast}:{toast:(s:string)=>void}){return <div><PageHeader title="Settings" subtitle="Company preferences and operational controls."/><div className="module-stat-grid">{["Company profile","Security","Notifications","Data & audit"].map((x,i)=><div className="module-stat" key={x}><span className="module-stat-icon">{["◈","✓","◔","▤"][i]}</span><small>{x}</small><b>Configured</b><span className="good">Available</span></div>)}</div><section className="panel module-workspace"><div className="empty-work"><div className="empty-icon">⚙</div><h3>Workspace controls</h3><p>Authentication, company isolation, audit logs, API access and operational modules are connected.</p><div className="quick-actions"><button className="button outline" onClick={()=>toast("Audit log API is enabled.")}>Audit logs</button><button className="button outline" onClick={()=>toast("API integration controls are enabled.")}>API access</button><button className="button primary" onClick={()=>toast("Settings are saved through protected API routes.")}>Save settings</button></div></div></section></div>}
function PageHeader({title,subtitle,actions}:{title:string;subtitle:string;actions?:React.ReactNode}){return <div className="page-header"><div><h1>{title}</h1><p>{subtitle}</p></div><div className="header-actions">{actions}</div></div>}
function PanelHead({title,action,onClick}:{title:string;action?:string;onClick?:()=>void}){return <div className="panel-head"><h2>{title}</h2>{action&&<button onClick={onClick}>{action} →</button>}</div>}
function Table({rows,columns}:{rows:Row[];columns:string[]}){return <div className="table-scroll"><table><thead><tr>{columns.map(c=><th key={c}>{label(c)}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i}>{columns.map(c=><td key={c}>{c==="status"||c==="isActive"?<Badge>{c==="isActive"?(r[c]?"Active":"Inactive"):r[c]}</Badge>:["total","amount","creditLimit","costPrice","salePrice","sales","collected"].includes(c)?<b>{money(r[c])}</b>:String(r[c]??"—")}</td>)}</tr>)}</tbody></table></div>}
createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);
